[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
start_command = "sh -c 'uvicorn src.mcp_server:app --host 0.0.0.0 --port ${PORT:-8000}'"
healthcheck_path = "/health"
healthcheck_timeout = 30

[variables]
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# services section not required for single service dockerfile builds
